Update planning_doc.Rmd
esciencecenter-digital-skills/template-docs-coordination pull request #12
Opened 2023-05-16 08:48 UTC by svenvanderburg

Added tasks to each role

2023-05-16 11:01 UTC, svenvanderburg reviewed
Thanks for the changes @FenneRiemslagh I added some comments!

2023-05-16 11:01 UTC, svenvanderburg commented on planning_doc.Rmd
> +
```suggestion
* Prepares the workshop website, collaborative documents, and exercises document.
* After the workshop: archives the collaborative documents and any other teaching material (for example slides or notebooks).
* In case of an a-la-carte workshop: ensure that the workshop is in line with the requirements from the client.

```

2023-05-16 11:01 UTC, svenvanderburg commented on planning_doc.Rmd
> +* Walks around to help attendees with small questions.
I think these tasks are for everyone, also the helpers.

2023-05-16 11:01 UTC, svenvanderburg commented on planning_doc.Rmd
> +* Walks around to help attendees with small questions.
So I suggest to either remove them or create a separate list of 'training team' responsibilities.

2023-05-16 11:01 UTC, svenvanderburg commented on planning_doc.Rmd
> +* Writes down things that went well and things to improve in the debriefing document.
Nice!

2023-05-16 11:01 UTC, svenvanderburg commented on planning_doc.Rmd
>  #### Discussion Points & Notes
@FenneRiemslagh can you also change 'Assign note taker' to 'Assign notetaker for this meeting'?

2023-05-22 08:26 UTC, mkuzak requested changes
Looks great, thank you! It should be ready after moving some of the Instructor's tasks to 'training team' responsibilities.

2023-05-22 08:26 UTC, mkuzak commented on planning_doc.Rmd
> +* Walks around to help attendees with small questions.
agree 👍🏻 better move to 'training team'

2023-05-23 12:56 UTC, FenneRiemslagh commented on planning_doc.Rmd
> +
Thanks!

2023-05-23 12:57 UTC, FenneRiemslagh commented on planning_doc.Rmd
> +* Walks around to help attendees with small questions.
Yes agree, I will make a separate list of training team.

2023-05-23 12:57 UTC, FenneRiemslagh commented on planning_doc.Rmd
>  #### Discussion Points & Notes
Yes will do!

2023-05-23 12:58 UTC, merged

2023-05-23 13:16 UTC, FenneRiemslagh commented
Sorry I first merged this pull request and next started a second one with the addition of the general training team tasks. I see now this could have been all inplemented into this branch. I will definately follow the 1 day github training in wageningen so i get better at this!